name: iOS CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build Project
        run: |
          cd example1_2
          xcodebuild clean build -project example1_2.xcodeproj -scheme example1_2 -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO